language: csharp
solution: WindowsFormsApp1.sln
install:
  - nuget restore WindowsFormsApp1.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release WindowsFormsApp1.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe
