configuration: Release
before_build:
  - nuget restore
build:
  verbosity:minimal
test:
  # only assemblies to test
  assemblies:
    only:
      - UnitTestWebApplication1\bin\Release\UnitTestWebApplication1.dll
